command:
  - python
  - -m
  - uvicorn
  - main:app
  - --host
  - 0.0.0.0
  - --port
  - "8000"
  - --workers
  - "1"

env:
  - name: DATABRICKS_CATALOG
    value: energy_copilot_catalog
  - name: LAKEBASE_DATABASE
    value: energy_copilot
  - name: LAKEBASE_USER
    value: energy_copilot_app
  - name: LOG_LEVEL
    value: INFO
  - name: PYTHONPATH
    value: /app
